<a href="https://colab.research.google.com/github/vidorc/PyTorch-for-Deep-Learning-A-Comprehensive-Study-Guide/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
random_tensor = torch.rand(10,10,10)

In [ ]:
random_tensor

tensor([[[0.8052, 0.9485, 0.6962, 0.3170, 0.9316, 0.9201, 0.1799, 0.3987,
          0.8904, 0.9111],
         [0.5888, 0.9204, 0.6471, 0.0879, 0.9407, 0.5106, 0.4860, 0.4032,
          0.3134, 0.1682],
         [0.4333, 0.0449, 0.3051, 0.2350, 0.8041, 0.6537, 0.4222, 0.9924,
          0.4374, 0.4859],
         [0.7876, 0.8421, 0.8936, 0.1430, 0.8725, 0.9863, 0.7860, 0.5784,
          0.3785, 0.3141],
         [0.5946, 0.1098, 0.1811, 0.4683, 0.4860, 0.5045, 0.0471, 0.4676,
          0.0318, 0.2781],
         [0.6237, 0.4609, 0.8029, 0.4058, 0.7677, 0.7706, 0.4589, 0.7111,
          0.0920, 0.9635],
         [0.0567, 0.6364, 0.7072, 0.4326, 0.0862, 0.9920, 0.8231, 0.8410,
          0.5124, 0.8447],
         [0.1334, 0.9151, 0.0348, 0.9514, 0.2707, 0.1690, 0.6121, 0.1231,
          0.7201, 0.5063],
         [0.4499, 0.2684, 0.0320, 0.3649, 0.5654, 0.6547, 0.6264, 0.5410,
          0.8486, 0.1014],
         [0.9861, 0.6656, 0.7579, 0.9305, 0.2082, 0.9609, 0.3898, 0.8881,
          0.6102,

In [ ]:
10*10*10


1000

In [ ]:
random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor

tensor([[[0.4451, 0.6453, 0.6364,  ..., 0.1085, 0.3593, 0.4091],
         [0.4432, 0.4015, 0.6032,  ..., 0.9546, 0.0929, 0.4874],
         [0.8839, 0.2087, 0.3250,  ..., 0.0355, 0.2916, 0.0810],
         ...,
         [0.6075, 0.6384, 0.4064,  ..., 0.9911, 0.0025, 0.7820],
         [0.6161, 0.8877, 0.3243,  ..., 0.2193, 0.0328, 0.0044],
         [0.4860, 0.7318, 0.0627,  ..., 0.5250, 0.3967, 0.6420]],

        [[0.4551, 0.3830, 0.1115,  ..., 0.4908, 0.4021, 0.4091],
         [0.8145, 0.1836, 0.6597,  ..., 0.0795, 0.5188, 0.6212],
         [0.0356, 0.8605, 0.1720,  ..., 0.3597, 0.1137, 0.4463],
         ...,
         [0.0560, 0.9788, 0.4602,  ..., 0.9951, 0.3577, 0.6300],
         [0.9019, 0.4909, 0.9475,  ..., 0.1612, 0.3403, 0.7665],
         [0.6849, 0.4758, 0.4563,  ..., 0.9192, 0.8010, 0.8457]],

        [[0.6683, 0.3376, 0.4549,  ..., 0.9517, 0.5414, 0.4924],
         [0.5100, 0.5444, 0.9314,  ..., 0.6143, 0.6904, 0.6000],
         [0.5516, 0.6361, 0.6287,  ..., 0.5107, 0.6575, 0.

In [ ]:
torch.Size((3,224,224))

torch.Size([3, 224, 224])

In [ ]:
zeroes = torch.zeros(size=(3,224,224))
zeroes

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [ ]:
OP = torch.ones(size=(3,224,224))
OP

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [ ]:
torch.float32

torch.float32

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=0,end=1100,step=12)
one_to_ten

tensor([   0,   12,   24,   36,   48,   60,   72,   84,   96,  108,  120,  132,
         144,  156,  168,  180,  192,  204,  216,  228,  240,  252,  264,  276,
         288,  300,  312,  324,  336,  348,  360,  372,  384,  396,  408,  420,
         432,  444,  456,  468,  480,  492,  504,  516,  528,  540,  552,  564,
         576,  588,  600,  612,  624,  636,  648,  660,  672,  684,  696,  708,
         720,  732,  744,  756,  768,  780,  792,  804,  816,  828,  840,  852,
         864,  876,  888,  900,  912,  924,  936,  948,  960,  972,  984,  996,
        1008, 1020, 1032, 1044, 1056, 1068, 1080, 1092])

In [ ]:
one_to_ten

tensor([   0,   12,   24,   36,   48,   60,   72,   84,   96,  108,  120,  132,
         144,  156,  168,  180,  192,  204,  216,  228,  240,  252,  264,  276,
         288,  300,  312,  324,  336,  348,  360,  372,  384,  396,  408,  420,
         432,  444,  456,  468,  480,  492,  504,  516,  528,  540,  552,  564,
         576,  588,  600,  612,  624,  636,  648,  660,  672,  684,  696,  708,
         720,  732,  744,  756,  768,  780,  792,  804,  816,  828,  840,  852,
         864,  876,  888,  900,  912,  924,  936,  948,  960,  972,  984,  996,
        1008, 1020, 1032, 1044, 1056, 1068, 1080, 1092])

In [ ]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
flaot_32 = torch.tensor([3.0,3.0,5.0], dtype=torch.float16
                        , device=None,
                        requires_grad=False)
flaot_32

tensor([3., 3., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor = flaot_32.type(torch.float16)
float_16_tensor

tensor([3., 3., 5.], dtype=torch.float16)

In [ ]:
int_32_tenor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tenor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * flaot_32

tensor([ 9.,  9., 25.], dtype=torch.float16)

In [ ]:
flaot_32 * int_32_tenor

tensor([ 9., 18., 45.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6700, 0.4018, 0.3229, 0.8939],
        [0.8111, 0.4841, 0.2443, 0.4139],
        [0.7202, 0.1625, 0.6003, 0.0504]])

In [ ]:
print(some_tensor)

tensor([[0.6700, 0.4018, 0.3229, 0.8939],
        [0.8111, 0.4841, 0.2443, 0.4139],
        [0.7202, 0.1625, 0.6003, 0.0504]])


In [ ]:
rand_tensor = torch.rand(10,10,10)

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 10
tensor * 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)


In [ ]:
torch.matmul(tensor , tensor)

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,10) , torch.rand(10,3))

tensor([[2.9017, 3.0456, 2.6538],
        [3.2032, 2.9812, 2.8217],
        [1.9557, 2.2496, 2.2625]])

In [ ]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.3320, 0.5003, 0.6212],
        [0.1433, 0.2254, 0.2694],
        [0.5150, 0.9443, 0.9880]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
tensor_b.shape, tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_b.T , tensor_b

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
tensor_b.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(tensor_A , tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Tensor: {tensor_A}\n")
print(f"Shape of tensor: {tensor_A.shape}\n")
print(f"Datatype of tensor: {tensor_A.dtype}\n")
print(f"Device tensor is on: {tensor_A.device}\n")


Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])

Shape of tensor: torch.Size([3, 2])

Datatype of tensor: torch.int64

Device tensor is on: cpu



In [ ]:
x=torch.arange(0,100,10)

In [ ]:
torch.min(x) , torch.max(x)

(tensor(0), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x[0]

tensor(0)

In [ ]:
x[9]

tensor(90)

In [ ]:
x = torch.arange(1. , 12.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([11]))

In [ ]:
x_reshaped = x.reshape(1,11)
x_reshaped , x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]),
 torch.Size([1, 11]))

In [ ]:
z = x.view(1,9)

RuntimeError: shape '[1, 9]' is invalid for input of size 11

In [ ]:
z,x

In [ ]:
x_stacked = torch.stack([x,x,x,], dim = 0)
x_stacked

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")

In [ ]:
x_reshaped.squeeze()

[x_reshaped.squeeze()]

In [ ]:
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

In [ ]:
x_orignal = torch.rand(size=(224,224,3))
x_permuted = x_orignal.permute(2,0,1)
x_orignal.shape , x_permuted.shape
print(f"Previous shape: {x_orignal.shape}")
print(f"New shape: {x_permuted.shape}")

In [ ]:
x_orignal[0,0,0] = 728218
x_orignal[0,0,0] , x_permuted[0,0,0]

In [ ]:
import torch
x = torch.arange(1, 10) .reshape(1,3,3)
x, x.shape

In [ ]:
x[0]
x[0][0]

In [ ]:
x[0][0][1]

In [ ]:
x[0,0:,2]

In [ ]:
import numpy as np
import torch
array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)
array , tensor

In [ ]:
array =+ 1
array , tensor

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

In [ ]:
tensor =+ 1
tensor

In [ ]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

In [ ]:
RANDOM_SEED = (42)
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu =tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
torch.rand(7,7)

tensor([[0.6287, 0.4778, 0.5222, 0.1466, 0.7072, 0.7361, 0.5486],
        [0.9882, 0.8676, 0.6539, 0.9288, 0.5022, 0.5773, 0.8957],
        [0.0827, 0.6159, 0.3979, 0.4597, 0.9377, 0.0214, 0.0481],
        [0.6718, 0.0142, 0.6210, 0.7183, 0.9036, 0.3820, 0.7212],
        [0.1381, 0.5263, 0.5464, 0.5624, 0.1541, 0.2073, 0.0952],
        [0.5167, 0.2078, 0.9625, 0.3091, 0.3588, 0.3499, 0.3326],
        [0.1035, 0.8705, 0.5392, 0.8790, 0.0648, 0.0834, 0.6008]])